# Generated by Django 3.2.5 on 2021-11-18 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='zipcode',
            new_name='zip_code',
        ),
    ]
